### ISSUE TITLE
Jname in  Array<Anime>

### ISSUE THREAD

**Issue by warlordsnet** [ghoshRitesh12/aniwatch-api#1]
Also, pls make this repo vercel/netlify compatible.
Add this in utils/method.ts
```ts
jname: $(el)
            .find(".film-detail .film-name .dynamic-name")
            .attr("data-jname")
            ?.trim() || null,
```
and this in /models/anime.ts

```ts
export interface Anime {
  id: string | null;
  name: string | null;
  jname: string | null;
  poster: string | null;
  duration: string | null;
  type: string | null;
  rating: string | null;
  episodes: {
    sub: number | null;
    dub: number | null;
  };
}
```

SIDE NOTE: 
remove your hardcoded api endpoint form the code.
```ts
setInterval(() => {
  console.log("HEALTHCHECK ;)", new Date().toLocaleString());
  https.get("/health");
}, 540000);
```

Also, add an if statement in the rate limit so that when people directly deploy this repo, they don't rate limit err.
```ts
import { rateLimit } from "express-rate-limit";

export const ratelimit = (req, res, next) => {
  if (req.hostname === 'api-aniwatch.onrender.com') {
    rateLimit({
      windowMs: 30 * 60 * 1000,
      max: 70,
      legacyHeaders: true,
      standardHeaders: "draft-7",
      message: "Too many API requests, try again later",
    })(req, res, next);
  } else {
    next();
  }
};
```

**Comment by ghoshRitesh12** [comment]
Hey @warlordsnet, thanks for opening an issue. 
I will take your suggestions into account and make these changes in a future release.

**Comment by warlordsnet** [comment]
> Hey @warlordsnet, thanks for opening an issue. I will take your suggestions into account and make these changes in a future release.

yes thank you, what would really be nice is vercel support as render.com is really unreliable.

**Comment by ghoshRitesh12** [comment]
> yes thank you, what would really be nice is vercel support as render.com is really unreliable.
Yeah I know rendr.com is slow too, but node deployments on vercel has some problems, I'll try to make this api vercel compatible.

**Comment by ghoshRitesh12** [comment]
> This is really an reliable project as consumet is heavy and doesn't have much features with aniwatch. Also, please do add anime schedule scraper. I would really appreciate it.
> 
> Also add nextAir date for anime also.
> 
> ```ts
> const nextAir = $('#schedule-date').attr('data-value');
>   res.nextAir = nextAir;
> ```

Yeah @consumet.ts is really heavy with their categories, hence I decided to scrape aniwatch only, also because it's quite resourceful. Also I'll take the nextAirDate into consideration and make these changes in a future PR.

**Comment by ghoshRitesh12** [comment]
@warlordsnet closing this issue as many of the features requested have been addressed.
