### ISSUE TITLE
Get skip times for episodes

### ISSUE THREAD

**Issue by RazeViana** [ghoshRitesh12/aniwatch-api#10]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
It would be nice if you retrieved the intro and outro skip times on the episodes.

**Describe alternatives you've considered**
I tried using the Aniskip API but I cannot seem to get the mappings correct as they use MAL Id instead of the episodeId provided in this API

**Additional context**
Nope

**Comment by RazeViana** [comment]
Additionally I think just adding the MAL ID to the Get Info API will also help as it will allow me to use the [Aniskip API](https://api.aniskip.com/api-docs#/skip-times/SkipTimesControllerV1_getSkipTimes) as well.

**Comment by ghoshRitesh12** [comment]
> Additionally I think just adding the MAL ID to the Get Info endpoint will also help as it will allow me to use the [Aniskip API](https://api.aniskip.com/api-docs#/skip-times/SkipTimesControllerV1_getSkipTimes) as well.

Yeah, this can definitely be done.

**Comment by ghoshRitesh12** [comment]
> Additionally I think just adding the MAL ID to the Get Info endpoint will also help as it will allow me to use the [Aniskip API](https://api.aniskip.com/api-docs#/skip-times/SkipTimesControllerV1_getSkipTimes) as well.

So just adding the MAL ID will do it right?

**Comment by RazeViana** [comment]
> > Additionally I think just adding the MAL ID to the Get Info endpoint will also help as it will allow me to use the [Aniskip API](https://api.aniskip.com/api-docs#/skip-times/SkipTimesControllerV1_getSkipTimes) as well.
> 
> 
> 
> @RazeViana  So just adding the MAL ID will do it right?

Yes, the MAL ID or Anilist ID. I would prefer Anilist but whatever works for you. 😅

**Comment by ghoshRitesh12** [comment]
Hey, I have added Anilist Id in episode srcs endpoint response. Closing this as completed. If you have any further issues in the api don't hesitate to open an issue.
