### ISSUE TITLE
Feature request : Estimated Schedule

### ISSUE THREAD

**Issue by anilove2** [ghoshRitesh12/aniwatch-api#12]
Hello there, I like your work,
if possible would you like to add " Estimated Schedule " which is on the home page of Aniwatch

**Comment by ghoshRitesh12** [comment]
Yeah, I have had that in mind for a while. I will add this in a future release.

**Comment by ghoshRitesh12** [comment]
@anilove2 Hey, I have added the feature. Check out the docs for the [endpoint](https://github.com/ghoshRitesh12/aniwatch-api/tree/est-schedule?tab=readme-ov-file#get-estimated-schedules)

**Comment by anilove2** [comment]
धन्यवाद आपका I 🙏

**Comment by ghoshRitesh12** [comment]
> धन्यवाद आपका I 🙏
🌚
