### ISSUE TITLE
zoro streaming links 

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [ghoshRitesh12/aniwatch-api#14]
Bro are you taking episode streaming links part from consumet cuz i was previously using their api their zoro streaming links are not working but yours are whats the difference 
I am specifically taking about this file https://github.com/ghoshRitesh12/aniwatch-api/blob/main/src/extractors/rapidcloud.ts
because before this the code is same.

**Comment by ghoshRitesh12** [comment]
@Shuvadip-Ghosh 

Well, yes I have taken consumet's extractor. I try to keep the extractors updated as their's, so there shouldn't be any difference at all.

**Comment by Shuvadip-Ghosh** [comment]
bro i tested both just now the links i get from your api is working but the links from consumet package is not working there has to be some difference please bro I need it !!!

**Comment by ghoshRitesh12** [comment]
> @ghoshRitesh12 bro i tested both just now the links i get from your api is working but the links from consumet package is not working there has to be some difference please bro I need it !!!

@Shuvadip-Ghosh 
It's the same extractor, I just checked. They may have some proxy issues.

**Comment by Shuvadip-Ghosh** [comment]
bro the vidcloud streaming link are not working what to do ?? the decoded m3u8 links are not working what to do ??

**Comment by ghoshRitesh12** [comment]
Aniwatch doesn't have a server named vidcloud. 
Need more clarification.
