### ISSUE TITLE
Wrong key used in `/episode-srcs`

### ISSUE THREAD

**Issue by WBRK-dev** [ghoshRitesh12/aniwatch-api#17]
### Describe the bug

In the route `/episode-srcs` an anilist id is given, but it actually is a MAL ID. For example if you go to `/anime/episode-srcs?id=hanma-baki-son-of-ogre-2nd-season-18458?ep=104219` it will give you a MAL ID. MAL: https://myanimelist.net/anime/51318. ANILIST: https://anilist.co/anime/51318 [404].

### Expected behavior

```
{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
  anilistID: number | null **(must be a valid anilist id or change the key to malId)**
}
```

The anilistId key must give a valid anilist id or the key must be changed to malId for all id's.

### Actual behavior

```
{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
  anilistID: number | null
}
```

anilistId gives malId instead of anilist id.

### Additional context

I suggest just changing the key from anilistId to malId.
It was probably just a typo.

**Comment by ghoshRitesh12** [comment]
Well if it's an invalid id then that's aniwatch's fault. I am just scraping the data. One thing I can do it include the `mal_id` alongside the `anilist_id`

**Comment by WBRK-dev** [comment]
I thought aniwatch only provides a mal_id not an anilist_id.

**Comment by WBRK-dev** [comment]
When you export your watchlist from aniwatch it also only gives you a mal I'd with every anime.

**Comment by ghoshRitesh12** [comment]
@WBRK-dev so only adding the mal_id will do right?

**Comment by WBRK-dev** [comment]
Oh I didn't know that. What you mentioned resolves this, if I understand you correctly.
