### ISSUE TITLE
topAiringAnimes provide additional animes from other category

### ISSUE THREAD

**Issue by Rohit3523** [ghoshRitesh12/aniwatch-api#2]
### Describe the bug

topAiringAnimes is providing animes from "Most Popular", "Most Favorite", "Latest Completed"

### Expected behavior

topAiringAnimes should onlt contains 5 animes because in home page, "Top Airing" has only 5 animes displayed and rest are hidden in view more button

### Actual behavior

It is also adding animes "Most Popular", "Most Favorite", "Latest Completed" categories.

**Comment by ghoshRitesh12** [comment]
topAiringAnimes are only displaying 5 animes, but the intetion is to get all the animes as it's an api. The people using this api can filter it in frontend.
