### ISSUE TITLE
hi I have a problem with api

### ISSUE THREAD

**Issue by lucaricci92** [ghoshRitesh12/aniwatch-api#20]
### Describe the bug

hi I have a problem with api

### Expected behavior

Hi, when I use the bees to extract the URL to watch movies I often get this error
{"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}
how can I solve it?

https://api-aniwatch.onrender.com/anime/episode-srcs?id=steinsgate-3?ep=230&server=vidstreaming&category=dub

### Actual behavior

Hi, when I use the bees to extract the URL to watch movies I often get this error
{"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}
how can I solve it?

https://api-aniwatch.onrender.com/anime/episode-srcs?id=steinsgate-3?ep=230&server=vidstreaming&category=dub

### Additional context

Hi, when I use the bees to extract the URL to watch movies I often get this error
{"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}
how can I solve it?

https://api-aniwatch.onrender.com/anime/episode-srcs?id=steinsgate-3?ep=230&server=vidstreaming&category=dub

**Comment by ghoshRitesh12** [comment]
Have a look at this issue #16

**Comment by lucaricci92** [comment]
thanks for the reply and above all for the library, I read the issie, in essence is it an effect that cannot be controlled? somehow and purely coincidental?

**Comment by ghoshRitesh12** [comment]
Yes it can't be controlled.

**Comment by ghoshRitesh12** [comment]
@lucaricci92 closing this issue right now. Let me know if any other issue appears.
