### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by jaephefd12** [ghoshRitesh12/aniwatch-api#24]
### Describe the bug

trying to decrypt key

### Expected behavior

Hey bro , 
Need small help from your side actually i am trying to make a script that can extract m3u8 from aniwatchtv

i found “source”: content but it is encrypted and it is salted  i need key for that can you tell me how can i find key from site and logic pls :)

### Actual behavior

.

**Comment by ghoshRitesh12** [comment]
@jaephefd12 this might be the resource for the keys: https://raw.githubusercontent.com/cinemaxhq/keys/e1/key, but it's not quite working

**Comment by jaephefd12** [comment]
Can you tell me like in which file there is key on site aniwatchtv like which i can scrape and how can i decrypt it i m trying find way but couldnt find anything  

https://raw.githubusercontent.com/cinemaxhq/keys/e1/key

this myb isnt working i tried ur repo but it is saying {"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}



And could you tell like how did u find that cinemaxhq/key/e1/key 

Give me some hints so i would try to find it will take not much time to ge… pls

**Comment by ghoshRitesh12** [comment]
> Can you tell me like in which file there is key on site aniwatchtv like which i can scrape and how can i decrypt it i m trying find way but couldnt find anything  
> 
> https://raw.githubusercontent.com/cinemaxhq/keys/e1/key
> 
> this myb isnt working i tried ur repo but it is saying {"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}
> 
> 
> 
> And could you tell like how did u find that cinemaxhq/key/e1/key 
> 
> Give me some hints so i would try to find it will take not much time to ge… pls

So I don't take any credits for the extractor of this API as its directly taken from [consumet](https://github.com/consumet/consumet.ts)

**Comment by animemandir** [comment]
I just checked consumet's discord, and many are trying to get the keys working. Try - https://keys4.fun/
@ghoshRitesh12 u should chk the cosumet and anify discord, maybe you'll find a clue about how to fix this scrape issues.

**Comment by ghoshRitesh12** [comment]
> I just checked consumet's discord, and many are trying to get the keys working. Try - https://keys4.fun/
> @ghoshRitesh12 u should chk the cosumet and anify discord, maybe you'll find a clue about how to fix this scrape issues.

I am already in their discord and I'll try the one you mentioned.

**Comment by ghoshRitesh12** [comment]
@animemandir, @jaephefd12 I have added another extractor for getting anime episodes. The response is a bit all over the place, I will arrange it sometime.

**Comment by animemandir** [comment]
it works decent. Server switching is not possible ig. idk why other servers wont work. it gives response only with the default server. Which gives only sub as default, this makes switching to dub impossible.

**Comment by ghoshRitesh12** [comment]
> it works decent. Server switching is not possible ig. idk why other servers wont work. it gives response only with the default server. Which gives only sub as default, this makes switching to dub impossible.

Aniwatch's vidstreaming and megacloud share the same servers ig and the rest dont work as well. You can choose dub in the api endpoint as category. So, it should solve the problem if I understood you correctly. Let me know if that's all.
