### ISSUE TITLE
Integration of Automated Builds

### ISSUE THREAD

**Issue by ayushch80** [ghoshRitesh12/aniwatch-api#27]
# Integration of Automated Builds
## Overview
This feature request aims to implement the build process by integrating automated builds using Node.js v21 and GitHub Actions.
## Implementation
You can check out the example build file [here](https://github.com/ayushch80/aniwatch-api/blob/main/.github/workflows/build.yml). This build utilizes the implementation of the `--experimental-sea-config` option in Node.js v21.

> While there are still some alternatives like `nexe` and `pkg`, they fail to build Express apps.

## Benefits
- One significant benefit of implementing this feature is the ease of project initiation through a few clicks rather than executing commands.

## Testing
I've tested the Linux and Windows builds, and they don't seem to encounter any runtime problems. Additionally, they work fine with `.env` files.

**Comment by ghoshRitesh12** [comment]
Sounds like a good idea.
