### ISSUE TITLE
Status 521

### ISSUE THREAD

**Issue by anilove2** [ghoshRitesh12/aniwatch-api#28]
### Describe the bug

status":521,"message":"Something went wrong"}

### Expected behavior

Need home page data

### Actual behavior

status":521,"message":"Something went wrong"}

### Additional context

I hosted on vercel and also sync fork
My branch is up-to-date

**Comment by ghoshRitesh12** [comment]
@anilove2 which route was it?

**Comment by anilove2** [comment]
Get estimated Schedule
{"status":500,"message":"cheerio.load() expects a string"}

Get anime home page
{"spotlightAnimes":[],"trendingAnimes":[],"latestEpisodeAnimes":[],"topUpcomingAnimes":[],"top10Animes":{"today":[],"week":[],"month":[]},"topAiringAnimes":[],"genres":[]}

**Comment by ghoshRitesh12** [comment]
I'll see what I can do about it

**Comment by anilove2** [comment]
I deploy again and it's work 👍

**Comment by ghoshRitesh12** [comment]
> I deploy again and it's work 👍

Glad to hear it.
