### ISSUE TITLE
cheerio.load() expects a string status 500

### ISSUE THREAD

**Issue by AjaiNarayananS** [ghoshRitesh12/aniwatch-api#29]
### Describe the bug

not geting the server data other then vidstreaming

### Expected behavior

i was accessing hd-1 hd-2 other etc.. i want to get data 

### Actual behavior

i was getting cheerio.load() expects a string status 500 i don't know what should to doo

**Comment by ghoshRitesh12** [comment]
Well vidstreaming is the only good server they have, and the rest either doesn't work properly or doesn't work at all.

**Comment by ghoshRitesh12** [comment]
Vidstreaming is the only viable option for aniwatch. @AjaiNarayananS, I hope that helped. I am closing this issue; feel free to open it in case I missed something.
