### ISSUE TITLE
Cannot decrypt sources. Perhaps the key is invalid

### ISSUE THREAD

**Issue by warlordsnet** [ghoshRitesh12/aniwatch-api#3]
### Describe the bug

Episode source fetching doesnt work sometimes.

### Expected behavior

This should be response: 
```js
{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
}
```

### Actual behavior

```js
{"status":500,"message":"Cannot decrypt sources. Perhaps the key is invalid."}
```

InternalServerError: Something went wrong
    at scrapeAnimeEpisodeSources (E:\projects\aniwatch-api\dist\parsers\animeEpisodeSrcs.js:117:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAnimeEpisodeSources (E:\projects\aniwatch-api\dist\controllers\animeEpisodeSrcs.controller.js:19:22)
AxiosError: read ECONNRESET
    at AxiosError.from (E:\projects\aniwatch-api\node_modules\.pnpm\axios@1.4.0\node_modules\axios\dist\node\axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (E:\projects\aniwatch-api\node_modules\.pnpm\axios@1.4.0\node_modules\axios\dist\node\axios.cjs:3010:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (E:\projects\aniwatch-api\node_modules\.pnpm\follow-redirects@1.15.3\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  syscall: 'read',
  code: 'ECONNRESET',
  errno: -4077,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      Referer: 'https://aniwatch.to/watch/steinsgate-3?ep=230',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4692.71 Safari/537.36',
      'X-Requested-With': 'XMLHttpRequest',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://aniwatch.to/ajax/v2/episode/servers?episodeId=230',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/ajax/v2/episode/servers?episodeId=230',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      lookup: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'aniwatch.to',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/ajax/v2/episode/servers',
      search: '?episodeId=230'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /ajax/v2/episode/servers?episodeId=230 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Referer: https://aniwatch.to/watch/steinsgate-3?ep=230\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4692.71 Safari/537.36\r\n' +
        'X-Requested-With: XMLHttpRequest\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: aniwatch.to\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/ajax/v2/episode/servers?episodeId=230',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'aniwatch.to',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://aniwatch.to/ajax/v2/episode/servers?episodeId=230',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}

### Additional context

Also, another type of err is {"status":500,"message":"Something went wrong"}, same route.
sometimes this also - cheerio.load() expects a string.

Please do add - data-jp wherever possible.

**Comment by ghoshRitesh12** [comment]
Aniwatch's resources are decrypted, it needs to be encrypted via a key. This error likely means that the key was timed out and yes I'll work on that.

**Comment by ghoshRitesh12** [comment]
@warlordsnet I think this issue is solved, henceforth closing it.
