### ISSUE TITLE
Server Query on Get Streaming Links return "cheerio.load() expects a string" when using HD server.

### ISSUE THREAD

**Issue by evnx32** [ghoshRitesh12/aniwatch-api#31]
### Describe the bug

When i adding 'server' query with hd-1 or hd-2, it will return 'cheerio.load() expects a string'.

### Expected behavior

Example Links
https://api-aniwatch.onrender.com/anime/episode-srcs?id=frieren-beyond-journeys-end-18542%3Fep%3D107257&server=hd-1

what i expected is

{
  "tracks": [
    {
      "file": "https://s.megastatics.com/subtitle/9b258ea774bfd06f85f682f4fa38128e/eng-2.vtt",
      "label": "English",
      "kind": "captions",
      "default": true
    },
  ],
  "intro": {
    "start": 0,
    "end": 89
  },
  "outro": {
    "start": 1460,
    "end": 1549
  },
  "sources": [
    {
      "url": "someurl",
      "type": "hls"
    }
  ],
  "anilistID": 154587,
  "malID": 52991
}

### Actual behavior

But what i got is

{
  "status": 500,
  "message": "cheerio.load() expects a string"
}

### Additional context

But when i'm using 'vidstreaming' server, it's workin fine. Btw thanks for your works, i really appreciate it.

**Comment by ghoshRitesh12** [comment]
Well they have just named the servers as `hd-1` and `hd-2`. It's just vidstreaming and megacloud underneath.

**Comment by ghoshRitesh12** [comment]
@evnx32, I hope that clears the issue. If there's anything more, do reopen this issue.

**Comment by yusuftuncay** [comment]
Same issue here, but I see that it doesn't work on hianime.to either, just sometimes.. Spent a good couple hours implementing this feature, just to know that it doesn't work xD. There it is, a dropdown that does nothing.

![image](https://github.com/user-attachments/assets/fb5cbab1-0fa6-4fd4-9be3-9a661077bfb2)

**Comment by ghoshRitesh12** [comment]
> Same issue here, but I see that it doesn't work on hianime.to either, just sometimes.. Spent a good couple hours implementing this feature, just to know that it doesn't work xD. There it is, a dropdown that does nothing.
> 
> ![image](https://github.com/user-attachments/assets/fb5cbab1-0fa6-4fd4-9be3-9a661077bfb2)
> 

😂 It's all hianime man. If they have it then we have it. I am sorry for those hours you spent building that feature.

**Comment by yusuftuncay** [comment]
Nah obviously don't need to be sorry! Sorry for sounding so rude, I tried the fix of yesterday but episodes of different animes I tested still won't load hd-2 or hd-1, just vidstreaming. Anyway it isn't that important as every episode works anyway.

**Comment by ghoshRitesh12** [comment]
the thing is that older animes may not have hd-1 or hd-2 servers as they are relatively new

**Comment by WBRK-dev** [comment]
I just checked an old anime from 2003 and it has the hd-1 and hd-2 servers.
Maybe I just got lucky there but it seems that vidstreaming and vidcloud were just renamed to hd-1 and hd-2.

**Comment by ghoshRitesh12** [comment]
> I just checked an old anime from 2003 and it has the hd-1 and hd-2 servers. Maybe I just got lucky there but it seems that vidstreaming and vidcloud were just renamed to hd-1 and hd-2.

Yeah that is most likely
