### ISSUE TITLE
Search Empty

### ISSUE THREAD

**Issue by ejatapibeda** [ghoshRitesh12/aniwatch-api#32]
### Describe the bug

animes empty while search

### Expected behavior

when you search should be list of

`animes: [
    {
      id: string,
      name: string,
      poster: string,
      duration: string,
      type: string,
      rating: string,
      episodes: {
        sub: number,
        dub: number,
      }
    },
    {...},
  ],`

### Actual behavior

empty list

`{"animes":[],`

### Additional context

my search 

https://api-aniwatch.onrender.com/anime/search?q=titan&page=1

**Comment by ghoshRitesh12** [comment]
@ejatapibeda It's actually aniwatch's issue. As I've tried searching multiple terms, but nothing came up.
