### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by sbwgg** [ghoshRitesh12/aniwatch-api#33]
Add advanced search from hianime.to

Searching for gender, type, langage, status, date, seasons and rating.

**Comment by ghoshRitesh12** [comment]
I'll work on this as soon as hianime fixes their search feature; as it's not showing any results regardless of the search term.

**Comment by ghoshRitesh12** [comment]
@sbwgg nvm. It's working now. I'll add this feature.

**Comment by ghoshRitesh12** [comment]
@sbwgg, I've added the feature.
