### ISSUE TITLE
Characters and promotional material data

### ISSUE THREAD

**Issue by PranavPurwar** [ghoshRitesh12/aniwatch-api#35]
It would be really nice if we could somehow also extract `Characters & Voice Actors` and `Promotional Videos` data from the API.

**Additional context**
Currently, on using the `/info:id` endpoint, this data is not included, while its present on the actual site.

**Comment by ghoshRitesh12** [comment]
@PranavPurwar, I'll add these changes in a future release

**Comment by ghoshRitesh12** [comment]
@PranavPurwar the characters data is a lot, to be put in one request; that data is paginated and would take a lot of time to retrieve all of those characters and for the promotional videos, it could be done easily.

**Comment by WBRK-dev** [comment]
@PranavPurwar #44 [v1.33.0](https://github.com/ghoshRitesh12/aniwatch-api/releases/tag/v1.33.0)
Promotional material, characters and voice actors have been added to the `/info` endpoint.
