### ISSUE TITLE
Error whilst getting anime episode sources

### ISSUE THREAD

**Issue by WBRK-dev** [ghoshRitesh12/aniwatch-api#36]
### Describe the bug

The route "/episode-srcs" is not working.

### Expected behavior

When you send a request to the route `/episode-srcs` it gets the following error:
`error:1C80006B:Provider routines::wrong final block length`

Full url: `/episode-srcs?id=demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100590&category=dub`
Server: `megacloud`

### Actual behavior

When you send a request to the route `/episode-srcs` it should respond with the correct episode sources.

**Comment by ghoshRitesh12** [comment]
I'll try to fix this in a future release.

**Comment by WBRK-dev** [comment]
I found out that the megacloud extractor is outdated.
Megacloud extractor function `extractVariables` is not extracting the variables needed to create the secret. 
The regex used for getting these variables is outdated and needs to be remade.
I tried to fix the regex myself but with no luck. (I have little to none experience with regex)

**Comment by WBRK-dev** [comment]
I've created a pull request that should fix this issue.

**Comment by ghoshRitesh12** [comment]
> I've created a pull request that should fix this issue.

Thanks a lot @WBRK-dev. I wasn't able to pull it off.
