### ISSUE TITLE
Error getting Anime Episode Sources

### ISSUE THREAD

**Issue by Akai771** [ghoshRitesh12/aniwatch-api#37]
### Describe the bug

"/episode-srcs" is not working

### Expected behavior

When you send a request to "/episode-srcs" it shows the anime episode source for the video

### Actual behavior

When you send a request to "/episode-srcs" it shows the following error:
**_error:1C80006B:Provider routines::wrong final block length_**

**Comment by ghoshRitesh12** [comment]
I'll try to fix this in a future release.

**Comment by RazeViana** [comment]
I also seem to be getting this issue (my project is not usable). Do you have an eta on the next release?

**Comment by Akai771** [comment]
> I also seem to be getting this issue (my project is not usable). Do you have an eta on the next release?

Or what needs to be changed in the code? so that it starts displaying Anime Episode Srcs

**Comment by RazeViana** [comment]
Yes I need the Anime Episode Srcs :)

**Comment by ghoshRitesh12** [comment]
Since @Akai771 has an obligation, I'll try my best to fix this issue within 2 days.

**Comment by ghoshRitesh12** [comment]
Hey, I tried to resolve this issue, but to no avail I wasn't able to. The issue is regarding the keys that are being extracted from the source

**Comment by RazeViana** [comment]
So it's not your end but an issue with the source?

**Comment by ghoshRitesh12** [comment]
> Contributor
yes

**Comment by RazeViana** [comment]
are there any alternatives?

**Comment by ghoshRitesh12** [comment]
> are there any alternatives?

Anicrush's servers may work, but I have to see whether their keys are also extractable or not. If that happens then I'll map hianimes id to anicrush (if I find any api or resource)

**Comment by RazeViana** [comment]
what about [zoro](https://zoroxtv.to) ?

**Comment by ghoshRitesh12** [comment]
Guys the issue has been fixed. Huge thanks to @WBRK-dev and @itzzzme for coming up with the solution ❤️
