### ISSUE TITLE
Trouble Understanding "18 4" Data

### ISSUE THREAD

**Issue by wm-jenildgohel** [ghoshRitesh12/aniwatch-api#4]
### Describe the bug

Trouble Understanding "18 4" Data

### Expected behavior

otherInfo: [
"TV",
"24m",
"Jul 7, 2023",
"HD",
{
'''sub_language_count" : 18,
''dub_language_count" : 4
}
]

### Actual behavior

otherInfo: [
"TV",
"24m",
"Jul 7, 2023",
"HD",
"18

    4"
]

**Comment by ghoshRitesh12** [comment]
@wm-jenildgohel hey can you state which endpoint was it?

**Comment by wm-jenildgohel** [comment]
/anime/home

**Comment by ghoshRitesh12** [comment]
> /anime/home

thanks for info, I will fix this bug in a future release
