### ISSUE TITLE
Add Rating Feature for Anime

### ISSUE THREAD

**Issue by d3vAdrian** [ghoshRitesh12/aniwatch-api#40]
-Introducing a rating feature for anime would enable users to share their opinions and may contribute to the platform's community-driven content evaluation systems maybe.
- Implement moderation tools to ensure the integrity and accuracy of anime ratings, such as flagging inappropriate or misleading ratings.
- In conclusion, I believe that adding a rating feature for anime content would significantly enrich the user experience

**Comment by WBRK-dev** [comment]
I believe this is something you should implement in your own application.
This is only a scraper adding such functionality to this api will require it to have its own database and user authentication.
