### ISSUE TITLE
Episode Source endpoint returns status 500 for RAW server in Hianime

### ISSUE THREAD

**Issue by RazeViana** [ghoshRitesh12/aniwatch-api#42]
### Describe the bug

When you try to call the episode source endpoint for an anime episode that only has the RAW server (on HiAnime) it returns 500 status code.

### Expected behavior

Return the episode source objects.

### Actual behavior

When using this server on HiAnime
![image](https://github.com/ghoshRitesh12/aniwatch-api/assets/57551859/8e2d9154-7e84-4856-a99d-9ee29688bd1e)

It returns status 500.

### Additional context

This error occurs in newer episodes that are recently released.

**Comment by WBRK-dev** [comment]
What does the error message say?

**Comment by RazeViana** [comment]
I'm not at my pc now but it was something along the lines of "can't find server"

**Comment by WBRK-dev** [comment]
Which anime has the raw server?
Then I can have a look at it myself.
:smiley:

**Comment by RazeViana** [comment]
So far this [one](https://hianime.to/watch/konosuba-gods-blessing-on-this-wonderful-world-3-19108?ep=123214) and this [one](https://hianime.to/watch/kaiju-no-8-19145?w=latest&ep=123747)

**Comment by WBRK-dev** [comment]
I am not getting any errors on raw servers. Are you sure you are using the latest version of the api?

**Comment by RazeViana** [comment]
This is the endpoint I am trying to use: `https://api-aniwatch.onrender.com/anime/episode-srcs?id=konosuba-gods-blessing-on-this-wonderful-world-3-19108?ep=123214`

**Comment by WBRK-dev** [comment]
You're right! There seems to be some kind of edge case on that specific episode.
I will have a look into that.

**Comment by WBRK-dev** [comment]
I've created a pr that should fix the problems you mentioned. #43
A fix for the current version is adding `&category=raw` to the `/episode-srcs` endpoint.

Example: `https://api-aniwatch.onrender.com/anime/episode-srcs?id=konosuba-gods-blessing-on-this-wonderful-world-3-19108?ep=123214&category=raw`

**Comment by ghoshRitesh12** [comment]
@WBRK-dev thank for the quick fix

**Comment by RazeViana** [comment]
Great thanks!

**Comment by RazeViana** [comment]
BTW, is it possible to make it return the anime with RAW without the query parameter 'category'? Perhaps make it fallback to that if it gets a 500 by the default flow?

**Comment by WBRK-dev** [comment]
No, you need to check on your end what category you want to use.
The default is sub.
If there is a fallback then it would take much longer to get a response.

**Comment by RazeViana** [comment]
okay thanks, I can close the ticket now 💯
