### ISSUE TITLE
unrelated but useful

### ISSUE THREAD

**Issue by Gareryer** [ghoshRitesh12/aniwatch-api#45]
can you fix and update the original old source code?
This is a live version running the Original [SEEZ](https://seez.su/)
This is a live version running the old code [Website](https://smashystream.com/)
[Shoow-main.zip](https://github.com/kumarPraveen08/seez.io-clone-with-tmdb/files/14384184/Shoow-main.zip)

**Comment by WBRK-dev** [comment]
This is in no way related to this repo.
This issue should be closed.

**Comment by ghoshRitesh12** [comment]
> can you fix and update the original old source code?
> This is a live version running the Original [SEEZ](https://seez.su/)
> This is a live version running the old code [Website](https://smashystream.com/)
> [Shoow-main.zip](https://github.com/kumarPraveen08/seez.io-clone-with-tmdb/files/14384184/Shoow-main.zip)

Well, I don't see how that affects this repo. Closing this as not planned.
