### ISSUE TITLE
HLS streaming  url not working 

### ISSUE THREAD

**Issue by anime-kun32** [ghoshRitesh12/aniwatch-api#47]
### Describe the bug

The url for the videos (m3u8) is not working 

### Expected behavior

the video is supposed to play 

### Actual behavior

instead it is just loading  on the player

**Comment by ghoshRitesh12** [comment]
It may be CORS error, can you state the exact error?

**Comment by WBRK-dev** [comment]
CORS should not be the problem here.
Vidcloud has the header `Access-Control-Allow-Origin: *`.
It could be that your isp is blocking the domain where the sources are hosted on?

**Comment by WBRK-dev** [comment]
It also could be that you are putting the source url directly into the video src tag.
If so, please use hls.js or a similar library for parsing hls streams.

**Comment by ghoshRitesh12** [comment]
Closing it as of now, feel free to reopen it in case something comes up.
