### ISSUE TITLE
Aniwatch returning 404 for getting anime ep streaming link

### ISSUE THREAD

**Issue by Craftingnerf** [ghoshRitesh12/aniwatch-api#5]
### Describe the bug

when I make a request like the following : "https://api-aniwatch.onrender.com/anime/episode-srcs?id=spy-x-family-17977?ep=89506&server=vidstreaming&category=sub" it returns with error 404 instead of urls (like it did before)

### Expected behavior

request example :
`https://api-aniwatch.onrender.com/anime/episode-srcs?id=spy-x-family-17977?ep=89506&category=sub`
what should output : (shown in the "GET Anime Episode Streaming Links" section of the readme
```
{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
}
```

### Actual behavior

request example : 
`https://api-aniwatch.onrender.com/anime/episode-srcs?id=spy-x-family-17977?ep=89506&category=sub`
what it outputs : 
`{ status: 404, message: 'Not Found' } `

### Additional context

code :
```
import fetch from "node-fetch";

async function test() {
    let str = "https://api-aniwatch.onrender.com/anime/episode-srcs?id=spy-x-family-17977?ep=89506&server=vidstreaming&category=sub";
    console.log(str);

    const resp = await fetch(str);
    const data = await resp.json();
    console.log(data);
    return data;
}

test();
```
I also have this issue with my own API setup in a docker container on a Ubuntu Linux VM
my best guess on the issue would be that Aniwatch changed how it serves the video streaming links and the web-scraper cant get it for some reason
its also not Aniwatch being down as other requests (not streaming URL) requests go through, and I was able to still watch videos from Aniwatch
I was just looking an episode on Aniwatch and when I opened the network tab in the Ctrl+Shift+I menu (windows) it would immediately redirect me to the home page, so they may have implemented a script that blocks web-scrapers from getting the video streaming links

**Comment by PraveenSingh0930** [comment]
+1 @ghoshRitesh12

**Comment by ghoshRitesh12** [comment]
I think that maybe Aniwatch has changed their servers, but I'll see what I can do.

**Comment by Craftingnerf** [comment]
It appears to me that vidstreaming is down.
However when I try the other options (eg megacloud) it returns with { status: 500, message: 'cheerio.load() expects a string' }
Code used for testing : 
```
import fetch from "node-fetch";
async function test(){
    
    const resp = await fetch(
      "https://api-aniwatch.onrender.com/anime/episode-srcs?id=steinsgate-3?ep=230&server=megacloud&category=dub"
    );
    const data = await resp.json();
    console.log(data);
}
test();
```
Output : 
`{ status: 500, message: 'cheerio.load() expects a string' }`
I haven't worked on the scripts in a while (I wrote them about a week before the error first appeared) and I haven't touched them since.

**Comment by ghoshRitesh12** [comment]
> It appears to me that vidstreaming is down. However when I try the other options (eg megacloud) it returns with { status: 500, message: 'cheerio.load() expects a string' } Code used for testing :
> 
> ```
> import fetch from "node-fetch";
> async function test(){
>     
>     const resp = await fetch(
>       "https://api-aniwatch.onrender.com/anime/episode-srcs?id=steinsgate-3?ep=230&server=megacloud&category=dub"
>     );
>     const data = await resp.json();
>     console.log(data);
> }
> test();
> ```
> 
> Output : `{ status: 500, message: 'cheerio.load() expects a string' }` I haven't worked on the scripts in a while (I wrote them about a week before the error first appeared) and I haven't touched them since.

I am a bit busy at the moment, but I will try my best to fix this issue, or if anything unfixable comes up, I'll update the Readme file.

**Comment by ghoshRitesh12** [comment]
This issue has been resolved, you may try to get episode streaming links again, it should work like before.
