### ISSUE TITLE
Streaming endpoint not working 

### ISSUE THREAD

**Issue by anime-kun32** [ghoshRitesh12/aniwatch-api#50]
### Describe the bug

the api streaming endpoint or url isn't working 

### Expected behavior

{
  headers: {
    Referer: string,
    "User-Agent": string,
    ...
  },
  sources: [
    {
      url: string, // .m3u8 hls streaming file
      isM3U8: boolean,
      quality?: string,
    },
    {...}
  ],
  subtitles: [
    {
      lang: "English",
      url: string, // .vtt subtitle file
    },
    {...}
  ],
  anilistID: number | null,
  malID: number | null,
}

### Actual behavior

{
    "status": 500,
    "message": "error:1C80006B:Provider routines::wrong final block length"
}

**Comment by ghoshRitesh12** [comment]
Refer to #16

**Comment by itzzzme** [comment]
Hey the streaming link is not working because you are trying to decrypt those link. But now the case is that those servers doesn't encrypt their link anymore so you can just make a simple request to the server and get the decrypted link.

So you really don't have to decrypt those link using any method . That should solve the problem ig

Request: 
https://megacloud.tv/embed-2/ajax/e-1/getSources?id=eY95ba4giWHv

Response:
{
    "sources": [
        {
            "file": "https://fgh5.biananset.net/_v7/f877ebeebe0a613047d4e5f85385c11177b24cda7bdbccf58bcebc6e66fd986ce939105fd66efa1102caf04268238238eea0adbbab1d205bc6c85ff70892811e45e971dcac6e07804668b16d2462fe3d07da8daa33cf0e533389edaec618b6d1abaa608a19f18b6f1a4bd0fa49379e6644ae6ac6d9a404997bfcdd7c988d0ce1/master.m3u8",
            "type": "hls"
        }
    ],
    "tracks": [
        {
            "file": "https://s.megastatics.com/subtitle/15d8324272ebaa371f8a9a823023413f/15d8324272ebaa371f8a9a823023413f.vtt",
            "label": "English",
            "kind": "captions",
            "default": true
        },
        {
            "file": "https://s.megastatics.com/thumbnails/4227c1abca9bd9721841f532098e5a1a/thumbnails.vtt",
            "kind": "thumbnails"
        }
    ],
    "encrypted": false,
    "intro": {
        "start": 0,
        "end": 0
    },
    "outro": {
        "start": 2633,
        "end": 2875
    },
    "server": 4
}


My suggestion is comment out those lines which are trying to decrypting those links cause those are useless and causing the problem. I hope this helps. Hola !

**Comment by anime-kun32** [comment]
Could you like explain it more , thanks so how do I then get the decrypted link

**Comment by itzzzme** [comment]
@anime-kun32 

make request in this link: https://megacloud.tv/embed-2/ajax/e-1/getSources?id=eY95ba4giWHv

you will get the decrypted m3u8 link

**Comment by anime-kun32** [comment]
The new questions this , there was was a parameter in the request link 'id' where do I get this from

**Comment by itzzzme** [comment]
@anime-kun32 

bro why don't you open dev tool in chrome and observe the network traffic of that website instead of asking questions.
You will get knowledge as well as your answer. In open source you don't get spoonfed

**Comment by anime-kun32** [comment]
Thanks
