### ISSUE TITLE
503 error on calling API

### ISSUE THREAD

**Issue by naumantechie** [ghoshRitesh12/aniwatch-api#51]
### Describe the bug

Getting "This service has been suspended" while fetching data from the endpoint (https://api-aniwatch.onrender.com)

### Expected behavior

Expected behevior is to get data in JSON form by sending request to the given endpoints.

### Actual behavior

Instead of getting data, I'm getting 503 error (server not responding) stating message that "This service has been suspended"

**Comment by ghoshRitesh12** [comment]
The service has been suspended, due to high egree traffic.
You to deploy your own instance to use it.

**Comment by naumantechie** [comment]
Ahhaa, Thank you for the heads up. I'll then follow the steps mentioned in the referred link. :)
