### ISSUE TITLE
Hardcoded Subtitles

### ISSUE THREAD

**Issue by yusuftuncay** [ghoshRitesh12/aniwatch-api#53]
**Is your feature request related to a problem? Please describe.**
I’d like hardcoded subtitles because it’s really annoying to work with subtitle files. I tried testing all servers to maybe where a server is dedicated to hardcoded subtitles but I couldn’t find any,

**Describe the solution you'd like**
Getting an m3u8 url that has an episode with hardcoded subs in it

**Describe alternatives you've considered**
No alternatives, just implemented the .vvt file.

Endpoint example:
```/anime/episode-srcs?id=one-piece-100?ep=2142```

**Additional context**

**Comment by ghoshRitesh12** [comment]
The hard coded subtitles depend on the provider in question. If the provider has them then well and good if otherwise then nothing we can do about it.

**Comment by yusuftuncay** [comment]
Understood, just realized hianime also uses soft subtitles. Thank you!

**Comment by ghoshRitesh12** [comment]
You are welcome.
