### ISSUE TITLE
Image Rendering

### ISSUE THREAD

**Issue by KhadeerBashaShaik** [ghoshRitesh12/aniwatch-api#54]
### Describe the bug

Not able to Render the images on home page

### Expected behavior

Not able to Render the images on home page

### Actual behavior

the images on home page are not served properly

**Comment by ghoshRitesh12** [comment]
which image are you referring to here?

**Comment by KhadeerBashaShaik** [comment]
![image](https://github.com/ghoshRitesh12/aniwatch-api/assets/107292322/e9d9d6bf-eacd-480f-998d-6567637441d6)
![image](https://github.com/ghoshRitesh12/aniwatch-api/assets/107292322/f1f30a59-3f71-4414-a2c9-c5730a85e8d3)
at /home route of api
im getting these errors

**Comment by ghoshRitesh12** [comment]
![image](https://github.com/ghoshRitesh12/aniwatch-api/assets/101876769/8a2102be-19d8-40e3-8cfe-4747a1c26dd4)
but the image url of for example wind breaker anime is working

it maybe some other problem
