### ISSUE TITLE
Next airing episode data

### ISSUE THREAD

**Issue by yusuftuncay** [ghoshRitesh12/aniwatch-api#55]
**Is your feature request related to a problem? Please describe.**
On hianime.to, let's say One Piece, I can see that there's data for when the next episode will be released, is this possible to add in the api? I searched /episodes and /info and didn't find any data related to this.

**Describe alternatives you've considered**
Using consumet api and the anilistId provided by aniwatch api for this feature

**Comment by ghoshRitesh12** [comment]
An API endpoint for this already exists. [The docs.](https://github.com/ghoshRitesh12/aniwatch-api?tab=readme-ov-file#get-estimated-schedules)

**Comment by yusuftuncay** [comment]
I saw that, but it requires a date. I was probably not clear enough, but I meant a property in seconds or so that tells when a specific anime's next episode will be released.

This is how consumet shows it (at the bottom):

![image](https://github.com/ghoshRitesh12/aniwatch-api/assets/70652416/cdca1767-a28c-4f32-99da-b6b6e2e5a0d4)

**Comment by ghoshRitesh12** [comment]
Ohh got it. Yeah, I think we could add this feature like consumet.

**Comment by yusuftuncay** [comment]
All righty, thank you!

**Comment by ghoshRitesh12** [comment]
@yusuftuncay Hey, I've added the `airingTimestamp` and `secondsUntilAiring` properties to the `/schedule` endpoint response schema. 
Closing this as completed. Ff you have any other queries then feel free to open another issue.

**Comment by yusuftuncay** [comment]
@ghoshRitesh12 I have a question and couldn't ask it anywhere else, I don't see the options for all posibilites of "sort" values are when searching, I tried score and it works fine, but I want the "most watched" which I found that hianime has, tried "most-watched", "mostWatched" and other things but nothing works for that, is there even a value for sorting on most watched?

**Comment by ghoshRitesh12** [comment]
> @ghoshRitesh12 I have a question and couldn't ask it anywhere else, I don't see the options for all posibilites of "sort" values are when searching, I tried score and it works fine, but I want the "most watched" which I found that hianime has, tried "most-watched", "mostWatched" and other things but nothing works for that, is there even a value for sorting on most watched?

I recently checked and its not working on hianime.to

**Comment by yusuftuncay** [comment]
Oh okay, it does work now in your api. Just checked hianime and it works there as well. Thanks a lot! By the way, I implemented so many functions on my website using your api, I'm thankful that you created this! Everything loads so fast and has literally no bugs compared to consumet. Oh and this is [the website](https://letswatch.site ) if you feel like checking it out.

**Comment by yusuftuncay** [comment]
Sorry for disturbing you, but what is the quality of an episode by default? Because I can see it's not 1080p comparing to hianime.to, same episode, same timeframe.

**Comment by ghoshRitesh12** [comment]
> Oh okay, it does work now in your api. Just checked hianime and it works there as well. Thanks a lot! By the way, I implemented so many functions on my website using your api, I'm thankful that you created this! Everything loads so fast and has literally no bugs compared to consumet. Oh and this is [the website](https://letswatch.site ) if you feel like checking it out.

Thank you so much ❤️
