### ISSUE TITLE
Can't open through vps 

### ISSUE THREAD

**Issue by Kisaramax** [ghoshRitesh12/aniwatch-api#57]
I tried to use this in my vps(through docker) & when I go to that ip it says "This page isn’t working If the problem continues, contact the site owner.
HTTP ERROR 400"

what should I do?

**Comment by ghoshRitesh12** [comment]
can you provide a screenshot for better understanding

**Comment by Kisaramax** [comment]
![Screenshot from 2024-07-13 15-06-01](https://github.com/user-attachments/assets/90958e72-cd3e-493a-aa0c-95303ace6bfe)
here this is the response from vps shows when i trying to access it's ip (ex: 167.xx.xxx.xxx:4000)

this is how i started it on docker

![image](https://github.com/user-attachments/assets/29df76a2-a880-4f12-a7d3-75084eb96392)

**Comment by Kisaramax** [comment]
here this is the response from vps shows when i trying to access it's ip (ex: 167.xx.xxx.xxx:4000)
![Screenshot from 2024-07-13 15-14-10](https://github.com/user-attachments/assets/865efc42-f86e-4c9d-a594-9d6d50dca530)


this is how i started it on docker
![Screenshot from 2024-07-13 15-10-42](https://github.com/user-attachments/assets/650bd4ec-f907-4093-bae7-07879988ed90)

**Comment by ghoshRitesh12** [comment]
Try to ping the local deployment using `curl` and see whether it's returning an error or not.

For example something like `curl http://localhost:4000/anime/home`

**Comment by Kisaramax** [comment]
it returns correct results but when I tried to do same thing on local machine using ip it returns nothing like lt is limited to localhost

**Comment by ghoshRitesh12** [comment]
Maybe you are just hosting the api to the loop back url. Try hosting it on the network.

**Comment by WBRK-dev** [comment]
Check in the firewall of the vps if the port 4000 is forwarded.
Most likely only port 80/443 is forwarded.

**Comment by Kisaramax** [comment]
I found solution it is not happening due to firewall, anyway I used nginx reverse proxy to to expose it to internet & now it is working without any issue
