### ISSUE TITLE
Vercel support

### ISSUE THREAD

**Issue by vmxt** [ghoshRitesh12/aniwatch-api#7]
I am trying to browse through self-host but I don't think this would work on `vercel`. I am awaiting on this feature.

**Comment by ghoshRitesh12** [comment]
Alright, I'll make this api vercel deployment compatible in a future release 😊

**Comment by vmxt** [comment]
Looking forward to it thanks @ghoshRitesh12 will also make a doc site on this if I am able to work on this

**Comment by ghoshRitesh12** [comment]
@vmxt I made this api vercel deployment compatible, check it out. Also theres a one click deploy button in the readme under *Host your instance* section
