### ISSUE TITLE
 A question please 

### ISSUE THREAD

**Issue by anime-kun32** [ghoshRitesh12/aniwatch-api#70]
what do I include in the env to allow any kind of domain

**Comment by ghoshRitesh12** [comment]
![Screenshot_2024-10-25-18-48-58-75_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/7982ecf8-bd68-4cc0-ad75-2cfde2059509)

You can put the domains of the services that would communicate with your own hosted instance.
Eg: If you had a web app with a domain example1.com, then put that domain in the env named: for allowing the API to respond to requests from that domain.

**Comment by anime-kun32** [comment]
ok thanks
