### ISSUE TITLE
Timezoned Schedule

### ISSUE THREAD

**Issue by jonvicbarcenas** [ghoshRitesh12/aniwatch-api#73]
i recommend adding timezone on schedule

**Comment by ghoshRitesh12** [comment]
The raw response looks like this:
![image](https://github.com/user-attachments/assets/ce77af83-2f97-41dd-8cba-967b253909dd)

There's no way to determine the timezone of the schedule for the API to then parse and send it back.

**Comment by ghoshRitesh12** [comment]
@jonvicbarcenas I am closing this issue as of now, feel free to open it in case I missed something or something else.
