### ISSUE TITLE
I'm having trouble deploying 1.40.0

### ISSUE THREAD

**Issue by anime-kun32** [ghoshRitesh12/aniwatch-api#74]
I tried replying the ALTs stable version on vercel but I keep getting error logs 

npm error code 1
npm error path /vercel/path0/aniwatch-api-1.40.0
npm error command failed
npm error command sh -c husky install
npm error A complete log of this run can be found in: /vercel/.npm/_logs/2024-11-09T15_34_54_210Z-debug-0.log
Error: Command "npm install" exited with 1

**Comment by ghoshRitesh12** [comment]
@anime-kun32 Is this all the error? If not could you maybe share a more verbose error or screenshot of the same?

**Comment by anime-kun32** [comment]
Ok let me see

**Comment by anime-kun32** [comment]
![Screenshot_20241109-155801](https://github.com/user-attachments/assets/686346e6-c444-4dfb-abe0-79f57ddd74fb)
![Screenshot_20241109-155752](https://github.com/user-attachments/assets/90c7d01b-103f-4c2b-8109-b558c28bed5c)

**Comment by anime-kun32** [comment]
This is all I can get

**Comment by ghoshRitesh12** [comment]
@anime-kun32 try to use this command: `npm install --ignore-scripts`

**Comment by anime-kun32** [comment]
![Screenshot_20241109-214404](https://github.com/user-attachments/assets/b46568ad-12f0-49ec-98db-3699a5943477)
![Screenshot_20241109-214256](https://github.com/user-attachments/assets/1d14c9a2-18ff-41f7-a86d-b67334449aec)

**Comment by anime-kun32** [comment]
Try it again and here 
![Screenshot_20241110-083025](https://github.com/user-attachments/assets/9c0635c5-38bf-4489-a520-9f93377e3210)

**Comment by ghoshRitesh12** [comment]
> ![Screenshot_20241109-214404](https://github.com/user-attachments/assets/b46568ad-12f0-49ec-98db-3699a5943477)
> ![Screenshot_20241109-214256](https://github.com/user-attachments/assets/1d14c9a2-18ff-41f7-a86d-b67334449aec)
> 

This is the way of doing it with --ignore-scripts, but the public directory error is something else related to vercel config. I hope if you figure that out then the issue will be gone.

**Comment by ghoshRitesh12** [comment]
@anime-kun32 refer to this: https://stackoverflow.com/questions/75592472/no-output-directory-named-build-found-after-the-build-completed-you-can-confi

**Comment by ghoshRitesh12** [comment]
@anime-kun32 did it work?
