### ISSUE TITLE
streaming hls file not working

### ISSUE THREAD

**Issue by shivang2607** [ghoshRitesh12/aniwatch-api#76]
I am really sorry to ask this here but I didnt know where else to ask this, the m3u8 files that we are getting for the episodes (or hls files) I am using vidstack player to stream it...but after loading once, it keeps buffering and doesnt loads further, I am not sure whats the issue. Can someone guide me how to stream these hls files via vidstack player ?

Do i need to configure crossOrigin headers or what ?

**Comment by ghoshRitesh12** [comment]
@shivang2607 is it happening with multiple m3u8 files?

**Comment by shivang2607** [comment]
@ghoshRitesh12 

> @shivang2607 is it happening with multiple m3u8 files?

Most of the files, someone said it's due to cors error, but the vidstack player says buffering error. And without proxy it's streaming first few seconds then it stops preloadig and continuously buffers.

**Comment by ghoshRitesh12** [comment]
@shivang2607 Could you use a proxy and then check if it works or not?

**Comment by shivang2607** [comment]
> @shivang2607 Could you use a proxy and then check if it works or not?

Even after using proxy it loads first few segments then keeps buffering indefinitely, can it be possible due to server load itself from their side ?

**Comment by ghoshRitesh12** [comment]
@shivang2607 Then I think it has to be a CORS issue

**Comment by shivang2607** [comment]
> @shivang2607 Then I think it has to be a CORS issue

@ghoshRitesh12 but as I said, I have tried using proxy. And if it has to be cors error then why even few segments are loading ??

**Comment by ghoshRitesh12** [comment]
My bad didn't catch the first bit of context. I assume it has to be a server error of some sorts. Could you send the animeEpisodeId of the episode that your are trying to watch. I tried it yesterday with Blue Lock season 2 and it worked fine.

**Comment by shivang2607** [comment]
@ghoshRitesh12 
I tried streaming this episode of rurouni kenshin 

samurai-x-202?ep=4671 

(Don't seek and test, stream continuously).

**Comment by shivang2607** [comment]
@ghoshRitesh12 

I tried streaming this episode of rurouni kenshin 

samurai-x-202?ep=4671 

(Don't seek and test, stream continuously).

**Comment by shivang2607** [comment]
@ghoshRitesh12 

I tried streaming this episode of rurouni kenshin 

samurai-x-202?ep=4671 

(Don't seek and test, stream continuously).

**Comment by shivang2607** [comment]
It's perfectly working now, I guess the issue was mainly on the server end also I tweaked some configurations like max buffer length and max waiting time.

**Comment by shivang2607** [comment]
> @shivang2607 Ohh okay, thanks for letting me know. Also would love for you to share the project and go through it, if you don't mind.

@ghoshRitesh12 Project is still in development phase , though I would love to  talk more about the project on discord, my username is shivang4301 .

**Comment by ghoshRitesh12** [comment]
Alright thanks

**Comment by ghoshRitesh12** [comment]
@shivang2607 closing this issue
