### ISSUE TITLE
Streaming link URL not 

### ISSUE THREAD

**Issue by anime-kun32** [ghoshRitesh12/aniwatch-api#77]
### Describe the bug

Anime episode sources URL is not working

### Expected behavior

Normally plays the video 

### Actual behavior

Takes forever to load the load video,  time line stuck at 00:00

**Comment by WBRK-dev** [comment]
Similar issue here!

It seems that the source provider is returning 500 for some reason.
It could be that the source provider is blocking requests if the origin is not correct.

![image](https://github.com/user-attachments/assets/cba19995-e6dc-467d-acdb-9e7f7a0f0944)
![image](https://github.com/user-attachments/assets/c5e6d41b-8e2e-434b-8673-a58d967cf7ad)

**Comment by anime-kun32** [comment]
Just checked one  of the streaming URL for cors and cors is responsible for this (try it )[https://cors-test.codehappy.dev/?url=https%3A%2F%2Ffgh5.biananset.net%2F_v7%2F68d599cf606db1687408c36ef1bba53c02bad17fafb3734f86d0b112bba0a69b1c12c285a700d716f8f4b055dd1638bb1bf242c1df96e60b6fc633e3ab50baed78b31d0c5d0e7ea509c4ff6eb6ea94ffd3db37a8ec0e0b51ed2740c9302666d2586b1d06235622c932d25802334bcfdb9298f9c767a7b37571cfaa0a192a523c%2Fmaster.m3u8&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=get]

**Comment by WBRK-dev** [comment]
Yes, seems to work again. ^^

**Comment by anime-kun32** [comment]
The Streaming URL works now so no more issues
