### ISSUE TITLE
Anime Episodes Endpoint is not giving actual data 

### ISSUE THREAD

**Issue by zeyrishop** [ghoshRitesh12/aniwatch-api#82]
### Describe the bug

Endpoint not showing any data like video URL, tracks, into outro time

### Expected behavior

it should show all data but nothing there, you can see in the Actual behavior for that.

### Actual behavior

Just showing this 

{
  "success": true,
  "data": {
    "tracks": [],
    "sources": [],
    "anilistID": 151807,
    "malID": 52299
  }
}

**Comment by ghoshRitesh12** [comment]
could you share the exact endpoint you've used

**Comment by zeyrishop** [comment]
http://localhost:4000/api/v2/hianime/episode/sources?animeEpisodeId=steinsgate-3?ep=230&server=hd-1&category=dub

http://localhost:4000/api/v2/hianime/episode/sources?animeEpisodeId=demon-slayer-kimetsu-no-yaiba-swordsmith-village-arc-18056?ep=100090&server=hd-2&category=dub

like for all anime episodeID

**Comment by animegers** [comment]
he won't be able to reach a localhost link it only works for the user who hosted the api on their pc. 
check this link to see the actual error.

https://hi-api-ruby.vercel.app/api/v2/hianime/episode/sources?animeEpisodeId=dandadan-19319?ep=128368&server=hd-1&category=dub

{
  "success": true,
  "data": {
    "tracks": [],
    "sources": [],
    "anilistID": 132029,
    "malID": 57334
  }
}

**Comment by ghoshRitesh12** [comment]
@WBRK-dev, bro could you look into this issue for the time being? I'm asking this favour because I'm away from home and won't be available for the rest of the day. I would be able to look into this issue tomorrow.

**Comment by ghoshRitesh12** [comment]
@WBRK-dev this issue seems urgent

**Comment by WBRK-dev** [comment]
@ghoshRitesh12 
I'm currently at work.
I'm not able to work on this until 17:00~18:00 UTC+1

**Comment by samiulalim1** [comment]
**Megacloud changed their getSources url and parameters. I think this is the reason for this unexpected behavior.**

old:
```javascript
const X = "/embed-2/ajax/e-1/getSources?id=" + W;
```
new:
```javascript
var CX = "/embed-2/ajax/e-1/getSources?id=" + window.pid + "&v=" + CC + "&h=" + CX + "&b=" + C9;
```

**Comment by WBRK-dev** [comment]
As I thought, the source provider changed their encryption and decryption method again. 💀

**Comment by animegers** [comment]
Wow I saw it and Overlooked it. Now that i compair it wow shouldn't have
overlooked it...💀
