### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by Immortalmod6** [ghoshRitesh12/aniwatch-api#85]
### Describe the bug

sir i deploy you api but i dont know how t ouse it ?

### Expected behavior

can you give me aniwatch folder like its a api so how i use that i dont know plz help sir

### Actual behavior

mere madad kar do please , mere pass tha gogoaniem ka folder liek zoror waala per gogoanime anime uplaod nahi kar raha hai to meen app ki repo dheki plz , mughe us ka pura folder de do like script , mughe itna nahi aata

**Comment by PacaHat** [comment]
Neeche scroll karo aur aapko is API ko use karne ka documentation mil jayega. Agar aapke paas Kirixen se clone kiya hua Zoro hai, toh wo is API ke saath kaam nahi karega kyunki data fetching methods us codebase mein alag hain. Is naye API ke saath kaam karne ke liye aapko pura code modify karna padega. Agar aapko detailed explanation chahiye, toh is Discord server ko join karo.

https://discord.gg/hEaHHyya
